### PR TITLE
add parameter canAddRange

### PR DESCRIPTION
**Pull request by vinograd19**
fix for https://github.com/quarterto/Elessar/issues/99

### CODE REVIEW

**Comment by quarterto** [comment]
Aha, that's such a simple fix. Thanks! One thing before I merge: I'd appreciate if you wrote a test that fails on develop but works with this fix. The [change event test](https://github.com/quarterto/Elessar/blob/develop/test/functional.js#L605-L628) is a good starting point; run the tests with `make test`.

**Comment by vinograd19** [comment]
Can you describe the process of testing? I tried to use 'make' command but unfortunately even 'npm install' doesn't work properly on my machine

**Comment by quarterto** [comment]
> even 'npm install' doesn't work properly on my machine

Just for Elessar or for everything? What errors are you getting?

**Comment by vinograd19** [comment]
'esprima-six' error: no such package available
it is required by derequire

**Comment by quarterto** [comment]
Ugh, this again. I'll look at updating the dependencies.

**Comment by quarterto** [comment]
Ok, tests and dependencies all work now. Run the tests locally with `make test-local` (`make test` runs on Saucelabs, if you want to do that you'll have to get an account and [set up zuul](https://github.com/defunctzombie/zuul/wiki/Cloud-testing#2-educate-zuul)), but they'll run as part of the Travis PR build so it's not essential).

One last thing: I've set up semantic-release, so could you update the commit message to something like `fix: prevent change event being fired multiple times` please?

**Comment by vinograd19** [comment]
Here we go next

    /@semantic-release%2fcommit-analyzer', error: no such package available

**Comment by quarterto** [comment]
What's your npm version? Looks like you're on a version that doesn't support [scoped packages](https://docs.npmjs.com/getting-started/scoped-packages). You'll need to update to at least npm 2.7.

**Comment by vinograd19** [comment]
npm --version
3.3.12

node --version
v5.3.0

**Comment by quarterto** [comment]
Huh, that's weird. It installs just fine for me. Maybe `rm -rf node_modules ; npm cache clean`? (Sorry this is being such a pain!)

**Comment by vinograd19** [comment]
tried `rm -rf node_modules ; npm cache clean` with no effect, the problem still occurs.

Offtopic: don't you think to rewrite plugin with a coffee?  It has a class system inside the language and a better support of passing the context so you don't need to use `$.proxy`.  
I've tried to convert the whole code for my entire project and that is a result https://gist.github.com/vinograd19/b9895fbc58fbf1c5e750

**Comment by quarterto** [comment]
The only thing I can think of is you're using a non-standard npm registry? What does `npm config get registry` return? 

> don't you think to rewrite plugin with a coffee

Not going to happen :) Coffeescript increases barriers to contribution and as a language and compiler [has issues](https://github.com/satyr/coco/wiki/wtfcs). I'm more likely to introduce a [Babel](http://babeljs.io/) build step and gradually move to ES2015+ syntax, but that will probably come as part of a 2.0 rewrite that's long overdue.

**Pull request closed without merging**
